version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
      - redis
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/banking
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongo_data:
